name: SortLoot2Inv
version: ${projectVersion}
main: io.github.divios.sortloot2inv.SortLoot2Inv
api-version: 1.16
softdepend: [ProtocolLib]
commands:
  sortLoot2Inv:
    description: Enables/disables feature
    usage: /SortLoot2Inv

permissions:
  SortLoot2Inv.use:
    default: op
